name = "kuki-metal-list"  
type = "javascript"         

account_id = "29169fb33bd950bab8d9fbef17194eda"  # Your Cloudflare account ID
workers_dev = true               # Enables Workers Dev Mode
compatibility_date = "2025-12-08"  # Today's date for compatibility

# Define your assets
[[routable_asset]]
  path = "public/*"